name: pcrc
recipe: drupal9
env_file:
  - .env
config:
  webroot: docroot
  php: '8.1'
  via: nginx
  database: mariadb:10.4.25
services:
  defaults:
    type: php:8.1
  database:
    portforward: 3300
  node:
    api: 3
    type: node:18
    build_as_root:
      - apt-get update
      - apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    run:
      - "cd /app/tests/cypress && npm install && npm_config_no_npx_prompt | npx cypress install"
  appserver:
    build_as_root:
      - apt-get update
      - apt-get install libxss1
      - echo "Run additional build commands here. Run lando rebuild after updating this file."
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  npm-new:
    service: node
    cmd: npm
  cypress:
    service: node
    cmd: npx cypress
  node:
    service: node
    cmd: node
  npm:
    service: appserver
    cmd: /usr/bin/npm
