name: pcrc
recipe: drupal9
env_file:
  - .env
config:
  webroot: docroot
  php: '8.1'
  via: nginx
  database: mariadb:10.4.25
services:
  defaults:
    type: php:8.1
  database:
    portforward: 3300
  appserver:
    build_as_root:
      - apt-get update
      - apt-get install libxss1
      - echo "Run additional build commands here. Run lando rebuild after updating this file."
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt install -y ./google-chrome-stable_current_amd64.deb
      - rm google-chrome-stable_current_amd64.deb
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  npm:
    service: appserver
    cmd: /usr/bin/npm
