@api
@ghadminsecond
Feature: Check for taxonomy terms
  In order to have a functioning site
  As a user of the admin role
  I need to see the proper taxonomy terms

  Scenario: Admin user sees proper taxonomy terms when logged in
    Given I am logged in as a user with the "administrator" role

    When I go to "admin/structure/taxonomy/manage/category/overview"
    Then I should see "Category"

    When I go to "admin/structure/taxonomy/manage/font_classification/overview"
    Then I should see "Classification"
    Then I should see "display"
    Then I should see "handwriting"
    Then I should see "monospace"
    Then I should see "sans-serif"
    Then I should see "serif"

    When I go to "admin/structure/taxonomy/manage/conditions_studied/overview"
    Then I should see "Conditions Studied"
    Then I should see "Acute Kidney Injury"
    Then I should see "Amyotrophic Lateral Sclerosis (ALS)"
    Then I should see "Bacterial Endocarditis"
    Then I should see "Bladder (including Urethral) Cancer"
    Then I should see "Brain Cancer"
    Then I should see "Breast Cancer"
    Then I should see "Bronchiectasis"
    Then I should see "Cirrhosis (non-viral)"
    Then I should see "Colon, Rectal, or Anal cancer"
    Then I should see "Connective Tissue Disease"
    Then I should see "COPD (including emphysema and chronic bronchitis)"
    Then I should see "Coronary artery Disease (including Myocardial Infarction)"
    Then I should see "Cystic Fibrosis"
    Then I should see "Dementia"
    Then I should see "Diabetes (uncomplicated)"
    Then I should see "Diabetes (with end organ damage)"
    Then I should see "End-Stage Renal Disease"
    Then I should see "Head and Neck Cancer"
    Then I should see "Heart Failure"
    Then I should see "Hemi- or Para-plegia"
    Then I should see "HIV/AIDS"
    Then I should see "Ischemic colitis (including bowel perforation)"
    Then I should see "Leukemia (including MDS)"
    Then I should see "Lung (non-small cell)"
    Then I should see "Lung (small cell)"
    Then I should see "Lymphoma"
    Then I should see "Melanoma"
    Then I should see "Multiple contributing Conditions"
    Then I should see "Multiple Myeloma (including amyloidosis)"
    Then I should see "Multiple sclerosis"
    Then I should see "Osteomyelitis"
    Then I should see "Other Cancer"
    Then I should see "Other Cardiovascular Disease"
    Then I should see "Other GI Disease"
    Then I should see "Other Infectious Disease"
    Then I should see "Other Neurological Disease"
    Then I should see "Other Pulmonary Disease"
    Then I should see "Other Renal Disease"
    Then I should see "Other upper GI (liver, gastric esophageal, carcinoid, etc.) Cancer"
    Then I should see "Ovarian/peritoneal Cancer"
    Then I should see "Pancreatic Cancer"
    Then I should see "Parkinson’s Disease"
    Then I should see "Peripheral Vascular Disease"
    Then I should see "Pneumonia"
    Then I should see "Prostate Cancer"
    Then I should see "Pulmonary Fibrosis, ILD, and other restrictive lung disease"
    Then I should see "Pulmonary Hypertension"
    Then I should see "Renal Cancer"
    Then I should see "Restrictive Heart Disease"
    Then I should see "Severe debility"
    Then I should see "Severe GI bleed"
    Then I should see "Stroke (hemorrhagic)"
    Then I should see "Stroke (ischemic/embolic)"
    Then I should see "Thyroid Cancer"
    Then I should see "Traumatic Brain Injury (TBI)"
    Then I should see "Ulcer Disease"
    Then I should see "Uterine, Cervical, or Vaginal Cancer"
    Then I should see "Valvular Heart Disease"
    Then I should see "Viral Hepatitis/Cirrhosis"

    When I go to "admin/structure/taxonomy/manage/data_types/overview"
    Then I should see "Data Types"
    Then I should see "Mixed Methods"
    Then I should see "Qualitative"
    Then I should see "Quantitative"

    When I go to "admin/structure/taxonomy/manage/directory_lists/overview"
    Then I should see "Directory Lists"
    Then I should see "Membership Roster"
    Then I should see "Organizational Leads"

    When I go to "admin/structure/taxonomy/manage/news_types/overview"
    Then I should see "News Types"
    Then I should see "Announcements"
    Then I should see "Cores and Centers"
    Then I should see "Funding"
    Then I should see "In the News"
    Then I should see "Newsletters"
    Then I should see "PCRC Testimonials"
    Then I should see "Uncategorized"

    When I go to "admin/structure/taxonomy/manage/number_of_study_sites/overview"
    Then I should see "Number of Study Sites"
    Then I should see "1"
    Then I should see "2 – 4"
    Then I should see "5 – 10"
    Then I should see "11 - 15"
    Then I should see "> 15"

    When I go to "admin/structure/taxonomy/manage/organizations/overview"
    Then I should see "Organizations"
    Then I should see "Advocate Aurora Health"
    Then I should see "Akron Children's Hospital"
    Then I should see "Albert Einstein College of Medicine"
    Then I should see "Aspire Healthcare"
    Then I should see "Atrium Health"
    Then I should see "Augusta University"
    Then I should see "Augusta University-Children's Hospital of Georgia"
    Then I should see "Avera eCare SeniorCare"
    Then I should see "Baylor College of Medicine"
    Then I should see "Baylor University"
    Then I should see "Ben Gurion University"
    Then I should see "Beth Israel Deaconess Medical Center"
    Then I should see "Binghamton University"
    Then I should see "Blue Cross Blue Shield of Massachusetts"
    Then I should see "Bluegrass Care Navigators"
    Then I should see "Boise State University"
    Then I should see "Boston Children's Hospital"
    Then I should see "Boston College"
    Then I should see "Boston University"
    Then I should see "Bowling Green State University"
    Then I should see "Brigham and Women's Hospital"
    Then I should see "Brighton and Sussex Medical School"
    Then I should see "Brown University"
    Then I should see "California Health Sciences University"
    Then I should see "California State University, Los Angeles"
    Then I should see "Capital Caring Health & Worldwide Hospice Palliative Care Alliance"
    Then I should see "Care Dimensions"
    Then I should see "Care Partners Hospice / Mission Health"
    Then I should see "Case Western Reserve University"
    Then I should see "Cedars-Sinai Medical Center"
    Then I should see "Central Arkansas Veterans Healthcare System"
    Then I should see "Central Michigan University"
    Then I should see "Children's Hospital Colorado"
    Then I should see "Children's Hospital Los Angeles"
    Then I should see "Children's Hospital of Philadelphia"
    Then I should see "Children's Mercy Kansas"
    Then I should see "Children's National Hospital"
    Then I should see "Children’s Hospital of Wisconsin"
    Then I should see "City of Hope Medical Center"
    Then I should see "City University of New York"
    Then I should see "Clayton State University"
    Then I should see "Cleveland Clinic"
    Then I should see "Cleveland Clinic Foundation"
    Then I should see "Cohen Children's Medical Center of Northwell Health"
    Then I should see "Colorado State University"
    Then I should see "Columbia University"
    Then I should see "Compassus"
    Then I should see "Concord Centre for Palliative Care"
    Then I should see "Connecticut Children's Medical Center"
    Then I should see "Corewell Health"
    Then I should see "Cottage Health"
    Then I should see "Creighton University"
    Then I should see "Dana-Farber Cancer Institute"
    Then I should see "Darthmouth-Hitchcock"
    Then I should see "Dartmouth College"
    Then I should see "Denver Health"
    Then I should see "Duke University"
    Then I should see "Duke-National University of Singapore"
    Then I should see "Durham VA Health System"
    Then I should see "East Carolina University"
    Then I should see "Einstein Healthcare Network"
    Then I should see "Eisenhower Medical Center"
    Then I should see "Emory University"
    Then I should see "FHI 360"
    Then I should see "Florida Atlantic University"
    Then I should see "Florida State University"
    Then I should see "Fordham University"
    Then I should see "Four Seasons"
    Then I should see "Fox Chase Cancer Center"
    Then I should see "Fred Hutchinson Cancer Research Center"
    Then I should see "George Washington University"
    Then I should see "Georgetown University Medical Center"
    Then I should see "Goldfarb School of Nursing at Barnes Jewish College"
    Then I should see "Hackensack Meridian"
    Then I should see "Harvard University"
    Then I should see "Hospital for Sick Children"
    Then I should see "Hunter College"
    Then I should see "Indiana University"
    Then I should see "Intermountain's Primary Children's Hospital"
    Then I should see "JH Bayview Medical Center"
    Then I should see "John D Dingell VA Medical Center"
    Then I should see "johns hopkins"
    Then I should see "Johns Hopkins University"
    Then I should see "Johns Hopkins University School of Nursing"
    Then I should see "Joliot Curie Institute / Aristide Le Dantec Hospital"
    Then I should see "JPS Health Network"
    Then I should see "Kaiser of Northern California"
    Then I should see "Kaiser Permanente Colorado"
    Then I should see "Kaiser Permanente Northwest"
    Then I should see "Kaiser Permanente Washington Health Research Institute"
    Then I should see "Kennesaw State University"
    Then I should see "Kent State University"
    Then I should see "LeadingAge"
    Then I should see "Levine Cancer Institute"
    Then I should see "M Health Fairview"
    Then I should see "Maine Medical Center"
    Then I should see "Marquette University and Children's Wisconsin"
    Then I should see "Massachusetts General Hospital"
    Then I should see "Mayo Clinic"
    Then I should see "Medical College of Wisconsin"
    Then I should see "MedStar Health / Georgetown University"

    When I go to "admin/structure/taxonomy/manage/participant_age/overview"
    Then I should see "Participant Age"
    Then I should see "Adult"
    Then I should see "Geriatric"
    Then I should see "Pediatric"

    When I go to "admin/structure/taxonomy/manage/participant_ethnicity_collected/overview"
    Then I should see "Participant Ethnicity Collected"
    Then I should see "No"
    Then I should see "Yes"

    When I go to "admin/structure/taxonomy/manage/participant_race/overview"
    Then I should see "Participant Race"
    Then I should see "< 25% Non-Hispanic White"
    Then I should see "≥ 25% Non-Hispanic White"

    When I go to "admin/structure/taxonomy/manage/participant_sex/overview"
    Then I should see "Participant Sex"
    Then I should see "Both male and female participants"
    Then I should see "Only female participants"
    Then I should see "Only male participants"

    When I go to "admin/structure/taxonomy/manage/participant_types/overview"
    Then I should see "Participant Types"
    Then I should see "Caregiver"
    Then I should see "Health Care Provider"
    Then I should see "Patient"

    When I go to "admin/structure/taxonomy/manage/request_types/overview"
    Then I should see "Request Types"
    Then I should see "Approved Request"
    Then I should see "Request Deemed Not Feasible with Available Data"

    When I go to "admin/structure/taxonomy/manage/study_design/overview"
    Then I should see "Study Design"
    Then I should see "Intervention"
    Then I should see "Observational – cross-sectional"
    Then I should see "Observational – longitudinal"

    When I go to "admin/structure/taxonomy/manage/study_setting/overview"
    Then I should see "Study Setting"
    Then I should see "Assisted Living"
    Then I should see "Clinic-Ambulatory"
    Then I should see "Domiciliary-Boarding Home"
    Then I should see "Home"
    Then I should see "Hospital"
    Then I should see "Nursing Home"
    Then I should see "Other Setting"

    When I go to "admin/structure/taxonomy/manage/study_types/overview"
    Then I should see "Study Types"
    Then I should see "PCRC Pilot Funded Studies"
    Then I should see "PCRC Supported Trials"

    When I go to "admin/structure/taxonomy/manage/therapeutic_areas/overview"
    Then I should see "Therapeutic Areas"
    Then I should see "Cancers"
    Then I should see "Cardiovascular"
    Then I should see "Gastrointestinal"
    Then I should see "Hepatic"
    Then I should see "Infectious"
    Then I should see "Multi-Systemic"
    Then I should see "Neurologic/Neurodegenerative"
    Then I should see "Pulmonary"
    Then I should see "Renal"

    When I go to "admin/structure/taxonomy/manage/total_enrollment/overview"
    Then I should see "Total Enrollment"
    Then I should see "< 50"
    Then I should see "50 – 99"
    Then I should see "100 – 199"
    Then I should see "200 – 299"
    Then I should see "300 – 399"
    Then I should see "400 – 499"
    Then I should see "≥ 500"
