@admin-config
@api
@ghadmin
Feature: check admin config pages
  In order use admin pages
  As a user of the admin role
  I need to see certain pages exist

  Scenario: Admin user sees proper fields when logged in
    Given I am logged in as a user with the "administrator" role
    When I go to "admin/config/people/accounts"
    Then I should see "Account settings"
    When I go to "admin/config/people/accounts/fields"
    Then I should see "Affiliation"
    Then I should see "Are you a PCRC Member?"
    Then I should see "First name"
    Then I should see "Last name"
    Then I should see "Picture"
    When I go to "admin/config/people/captcha"
    Then I should see "CAPTCHA settings"

    When I go to "admin/config/system/site-information"
    Then the "edit-site-name" field should contain "Palliative Care Research Cooperative Group"
    Then the "edit-site-slogan" field should contain ""
    Then the "site_mail" field should contain "pcrc.disc@gmail.com"
    Then the "edit-site-frontpage" field should contain "/home"
    Then the "edit-site-403" field should contain ""
    Then the "edit-site-404" field should contain ""
    When I go to "admin/config/system/smtp"
    Then I should see "SMTP Authentication Support"
    When I go to "admin/config/system/cron"
    Then I should see "Cron"
    When I go to "admin/config/system/entity-clone"
    Then I should see "Entity clone settings"
    Then I should see "Aggregator feed"
    Then I should see "Aggregator feed item"
    Then I should see "Custom block"
    Then I should see "Comment"
    Then I should see "Contact message"
    Then I should see "Fake entity type"
    Then I should see "Entity subqueue"
    Then I should see "Subscription"
    Then I should see "Feed"
    Then I should see "File"
    Then I should see "Content"
    Then I should see "URL alias"
    Then I should see "Redirect"
    Then I should see "Search task"
    Then I should see "Shortcut link"
    Then I should see "Taxonomy term"
    Then I should see "User"
    Then I should see "Webform submission"
    Then I should see "Font"
    Then I should see "Custom menu link"

    When I go to "admin/config/content/entity_browser"
    Then I should see "browse_documents"
    Then I should see "browse_documents_modal"
    Then I should see "browse_files"
    Then I should see "browse_files_modal"
    Then I should see "browse_images"
    Then I should see "browse_images_modal"
    When I go to "admin/config/content/linkit"
    Then I should see "Linkit profiles"
    Then I should see "Administrator"
    When I go to "admin/config/content/formats"
    Then I should see "Full HTML"
    Then I should see "Restricted HTML"
    Then I should see "Basic HTML"
    Then I should see "Plain text"
    When I go to "admin/config/content/embed"
    Then I should see "Embed buttons"
    Then I should see "Document Browser"
    Then I should see "File Browser"
    Then I should see "Image Browser"
    Then I should see "Node"

    When I go to "admin/config/user-interface/admin-toolbar-search-settings"
    Then I should see "Admin toolbar search settings"
    When I go to "admin/config/user-interface/admin-toolbar-tools"
    Then I should see "Admin Toolbar Tools settings"
    When I go to "admin/config/user-interface/admin-toolbar"
    Then I should see "Admin Toolbar settings"
    When I go to "admin/config/user-interface/shortcut"
    Then I should see "Default"

    When I go to "admin/config/development/performance"
    Then I should see "Performance"
    When I go to "admin/config/development/logging"
    Then I should see "Logging and errors"
    When I go to "admin/config/development/maintenance"
    Then I should see "Maintenance mode"
    When I go to "admin/config/development/configuration"
    Then I should see "Synchronize"

    When I go to "admin/config/media/file-system"
    Then I should see "File system"
    When I go to "admin/config/media/image-styles"
    Then I should see "Directory Image"
    Then I should see "Directory profile"
    Then I should see "File Entity Browser small thumbnail"
    Then I should see "File Entity Browser thumbnail"
    Then I should see "Large (480×480)"
    Then I should see "Linkit result thumbnail"
    Then I should see "Max 325x325"
    Then I should see "Max 650x650"
    Then I should see "Max 1300x1300"
    Then I should see "Max 2600x2600"
    Then I should see "Medium (220×220)"
    Then I should see "Thumbnail (100×100)"
    Then I should see "Video Embed Wysiwyg: Thumbnail Preview"
    When I go to "admin/config/media/responsive-image-style"
    Then I should see "Responsive image styles"
    Then I should see "Narrow"
    Then I should see "Original"
    Then I should see "Wide"
    When I go to "admin/config/media/file-settings"
    Then I should see "File settings"
    When I go to "admin/config/media/responsive-image-style"
    Then I should see "Narrow"
    Then I should see "Original"
    Then I should see "Wide"
    When I go to "admin/config/media/image-toolkit"
    Then I should see "Image toolkit"

    When I go to "admin/config/search/path"
    Then I should see "URL aliases"
    When I go to "admin/config/search/search-api"
    Then I should see "Search API"
    When I go to "admin/config/search/simplesitemap"
    Then I should see "Simple XML Sitemap"
    When I go to "admin/config/search/redirect"
    Then I should see "Redirect"
    When I go to "admin/config/search/facets"
    Then I should see "facets"
    Then I should see "search_api:views_page__pcrc_search_content__search_content"
    Then I should see "search_api:views_page__pcrc_studies_search__page_1"

    When I go to "admin/config/regional/settings"
    Then I should see "Regional settings"
    When I go to "admin/config/regional/date-time"
    Then I should see "Date and time formats"
    When I go to "admin/config/regional/name"
    Then I should see "Family"
    Then I should see "Full"
    Then I should see "Given"
    Then I should see "Given Family"
    Then I should see "Title Family"

    When I go to "admin/config/services/addtoany"
    Then I should see "AddToAny"
    When I go to "admin/config/services/google-analytics"
    Then I should see "Google Analytics"
    When I go to "admin/config/services/rss-publishing"
    Then I should see "RSS publishing"
    When I go to "admin/config/services/aggregator"
    Then I should see "Aggregator"
    Then I should see "NIH Extramural Nexus"

    When I go to "admin/reports/status"
    Then I should see "Status report"
