<?php

/**
 * @file
 * Contains theme level customizations for the pcrc_omega theme
 */

/**
 * Implements hook_js_alter().
 */
function pcrc_omega_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {

} // END pcrc_omega_js_alter

/**
 * Implements hook_css_alter().
 */
function pcrc_omega_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {
  
} // END pcrc_omega_css_alter 

/**
 * Implements hook_page_attachments_alter().
 */
function pcrc_omega_page_attachments_alter (&$attachments) {
  
} // END pcrc_omega_page_attachments_alter

/**
 * Implements hook_preprocess().
 */
function pcrc_omega_preprocess(&$variables, $hook) {
  
} // END pcrc_omega_preprocess

/**
 * Implements hook_preprocess_HOOK() for html templates.
 */
function pcrc_omega_preprocess_html(&$variables) {
  
} // END pcrc_omega_preprocess_html

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function pcrc_omega_preprocess_page(&$variables) {
  
} // END pcrc_omega_preprocess_page

/**
 * Implements hook_preprocess_HOOK() for region templates.
 */
function pcrc_omega_preprocess_region(&$variables) {
  
} // END pcrc_omega_preprocess_region

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function pcrc_omega_preprocess_node(&$variables) {
  
} // END pcrc_omega_preprocess_node

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function pcrc_omega_preprocess_block(&$variables) {
  
} // END pcrc_omega_preprocess_block

/**
 * Implements hook_preprocess_HOOK() for field templates.
 */
function pcrc_omega_preprocess_field(&$vars) {
  
} // END pcrc_omega_preprocess_field

/**
 * Implements hook_html_head_alter()
 */
function pcrc_omega_html_head_alter(&$head_elements) {
  
} // END pcrc_omega_html_head_alter