name: (A) Database to artifact
on:
  workflow_dispatch:
  schedule:
    - cron:  '16 11 * * *'
jobs:
  build:
    name: Grab backup and fix backup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Lando
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-v3.18.0"
          sudo chmod +x /usr/local/bin/lando
        env:
          lando_verison: ${{ secrets.LANDO_VERSION }}
      - name: Setup Lando cache
        uses: actions/cache@v2
        with:
          path: ~/.lando/cache
          key: ${{ runner.os }}-lando-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-lando-${{ github.ref }}
      - name: Start Lando
        run: |
          echo 'docker compose --compatibility "$@"' > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose -v
          echo "$lando_env" > .env
          mkdir -p web/sites/default/settings
          cp blt/lando.local.settings.php web/sites/default/settings/local.settings.php
          docker -v
          docker-compose -v
          lando destroy -y
          lando start
        env:
          lando_env: ${{ secrets.LANDO_ENV }}
      - uses: ./.github/actions/dingorunner
        env:
          runner: bkup
          terminus_api: ${{ secrets.TERMINUS_API }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          site_name: ${{ secrets.TERMINUS_SITE_NAME }}
          env: live
      - name: Sync DB
        run: |
          lando composer config -g github-oauth.github.com $gh_token
          composer config -g github-oauth.github.com $gh_token
          composer install --ignore-platform-reqs
          lando db-import backups/site.sql.gz
          cd web
          lando drush cr
          lando drush deploy
          lando drush sql-sanitize --sanitize-password=y -y
          lando drush cr
          cd ..
          lando drush user-create therealrick --mail="therealrick@rickmorty.cn" --password="$pass"
          lando drush user-add-role "administrator" therealrick
          lando drush user-create therealmorty --mail="therealmorty@rickmorty.cn" --password="$pass"
          lando drush user-add-role "site_admin" therealmorty
          lando drush user-create therealbeth --mail="therealbeth@rickmorty.cn" --password="$pass"
          lando drush user-add-role "content_editor" therealbeth
          lando drush user-create theRealSummer --mail="therealsummer@rickmorty.cn" --password="$pass"
          lando drush user-add-role "pcrc_member" theRealSummer
          lando drush user-create therealjerry --mail="therealjerry@rickmorty.cn" --password="$pass"
          lando drush user-create therealbutterrobot --mail="therealbutterrobot@rickmorty.cn" --password="$pass"
          lando drush user-add-role "request" therealbutterrobot
          lando db-export site.sql
        env:
          gh_token: ${{ secrets.GH_TOKEN_REPO }}
          pass: ${{ secrets.TEST_USERS_PASSWORD }}
      - name: 'Upload Backup Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: daily-backup
          path: site.sql.gz
          retention-days: 7
