name: (M) Behat Tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      database:
        description: 'Recent database dump to use (leave empty to use artifact)'
permissions:
  actions: read
  contents: write
jobs:
  behat:
    name: Behat tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set the cache date
        id: set_cache_date
        run: |
          echo "CACHE_DATE=$(date "+%y%m%d")" >> $GITHUB_ENV
      - name: Install Lando
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-v3.18.0"
          sudo chmod +x /usr/local/bin/lando
      - name: Setup Lando cache
        uses: actions/cache@v3
        env:
          cache-name: lando
        with:
          path: ~/.lando/cache
          key: ${{ runner.os }}-lando
      - name: Spin up site
        run: |
          composer config -g github-oauth.github.com $gh_token
          composer install --ignore-platform-reqs -n
          vendor/bin/blt mih:landosetup $gh_token $uid
          sleep 30
        env:
          gh_token: ${{ secrets.GH_TOKEN_REPO }}
          uid: ${{ secrets.PCRC_UID }}
      - name: Custom Database
        if: "${{ github.event.inputs.database != '' }}"
        run: |
          rm backups/site.sql.gz
          wget -O backups/site.sql.gz '$database'
          lando db-import backups/site.sql.gz
          lando drush sql-sanitize --sanitize-password -y
        env:
          database: ${{ github.event.inputs.database }}
      - name: Run behat tests
        run: |
          lando blt mih:behat
        env:
          behat_tag: ${{ github.event.inputs.BEHAT_TAG }}
      - name: Screenshots artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tests/behat/screenshots
          retention-days: 1

