name: (M) Cypress Tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      database:
        description: 'Recent database dump to use (leave empty to use artifact)'
permissions:
  actions: read
  contents: write
jobs:
  behat:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set the cache date
        id: set_cache_date
        run: |
          echo "CACHE_DATE=$(date "+%y%m%d")" >> $GITHUB_ENV
      - name: Install Lando
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-v3.19.5"
          sudo chmod +x /usr/local/bin/lando
      - name: Spin up site
        run: |
          composer config -g github-oauth.github.com $gh_token
          composer install --ignore-platform-reqs -n
          vendor/bin/blt mih:landosetup $gh_token $uid
          ls -al docroot/modules/contrib
          echo '=-=-=-=-=-=-=-=-=-=-=-=-'
          ls -al docroot/modules/custom
          touch tests/cypress/cypress/fixtures/login-data.json
          echo $CYPRESS_LOGIN_DATA >> tests/cypress/cypress/fixtures/login-data.json
          ls tests/cypress/cypress/fixtures/
          cat tests/cypress/cypress/fixtures/login-data.json
          sleep 5
        env:
          gh_token: ${{ secrets.GH_TOKEN_REPO }}
          uid: ${{ secrets.PCRC_UID }}
          CYPRESS_LOGIN_DATA: ${{ secrets.CYPRESS_LOGIN_DATA }}
      - name: Custom Database
        if: "${{ github.event.inputs.database != '' }}"
        run: |
          rm backups/site.sql.gz
          wget -O backups/site.sql.gz '$database'
          lando db-import backups/site.sql.gz
          lando drush sql-sanitize --sanitize-password -y
        env:
          database: ${{ github.event.inputs.database }}
      - name: Run cypress tests
        run: |
          cd tests/cypress
          lando cypress run --config baseUrl=https://pcrc.lndo.site
        env:
          behat_tag: ${{ github.event.inputs.BEHAT_TAG }}
      - name: Test login data
        uses: actions/upload-artifact@v3
        with:
          name: login-data
          path: tests/cypress/cypress/fixtures/login-data.json
          retention-days: 1
      - name: Screenshots artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tests/cypress/cypress/screenshots
          retention-days: 1

