name: (A) Deploy to dev
on:
  push:
    branches:
      - 'main'
      - 'md-*'
jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#nobuild') }}
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: pcrc-1
        with:
          path: |
            vendor
            web/core
          key: ${{ env.cache-name }}
      - uses: ./.github/actions/dingorunner
        env:
          runner: update
          blt: ./vendor/bin/blt
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          message: ${{ github.event.head_commit.message }}
          gh_token: ${{ secrets.GH_TOKEN_REPO }}
  md:
    name: Spin up Multidev environment
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'md-') }}
    needs: deploy
    steps:
      - uses: actions/checkout@v1
      - name: Composer install
        run: |
          composer install
      - name: Check if multidev environment exists
        uses: ./.github/actions/dingorunner
        env:
          runner: md_check
          terminus_api: ${{ secrets.TERMINUS_API }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Store md status into env variable
        run: |
          MD_STATUS=$(cat md_check.txt)
          echo $MD_STATUS
          echo "md=$(echo $MD_STATUS)" >> $GITHUB_ENV
      - name: Create multidev environment
        uses: ./.github/actions/dingorunner
        if: ${{ env.md == 'false' }}
        env:
          runner: md_create
          terminus_api: ${{ secrets.TERMINUS_API }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
