name: (AM) Security Updates
on:
  workflow_dispatch:
  schedule:
    - cron:  '20 17,18,19,20,21 * * 3'
permissions:
  actions: read
  contents: write
  pull-requests: write
jobs:
  build:
    name: Check for security updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Lando
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-v3.11.0"
          sudo chmod +x /usr/local/bin/lando
      - name: Start Lando
        run: |
          echo "$lando_env" > .env
          echo "GITHUB_TOKEN=$GITHUB_ACTOR:$GITHUB_TOKEN" >> .env
          lando destroy -y
          lando start && lando xdebug-off
        env:
          lando_env: ${{ secrets.LANDO_ENV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      - name: Sync DB
        run: |
          composer config -g github-oauth.github.com $gh_token
          composer install --ignore-platform-reqs -n
          vendor/bin/blt mih:landosetup $gh_token $uid
        env:
          gh_token: ${{ secrets.GH_TOKEN_REPO }}
          uid: ${{ secrets.PCRC_UID }}
      - name: Run blt mih:su
        run: |
          vendor/bin/blt mih:su --no-interaction
        env:
          gh_token: ${{ secrets.GH_TOKEN_REPO }}

